default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Load App Store Connect API key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      duration: 1200,
      in_house: false
    )

    # Ensure certs/profiles are installed
    basicauth_b64 = ENV["MATCH_GIT_BASIC_AUTH_B64"].to_s.strip
    UI.user_error!("MATCH_GIT_BASIC_AUTH_B64 is empty") if basicauth_b64.empty?

    match(
      type: "appstore",
      readonly: true,
      git_basic_authorization: basicauth_b64 # IMPORTANT: raw b64 only
    )

    # Build ipa
    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    # Upload ipa to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: false
    )
  end
end
