default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    match(
      type: "appstore",
      readonly: true
    )

    build_app(
      scheme: "Runner",
      export_method: "app-store",
      output_name: "Runner.ipa",
      include_bitcode: false,
      clean: true,
      silent: false,
      skip_profile_detection: false,
      allowProvisioningUpdates: true,
      xcargs: "DEVELOPMENT_TEAM=#{ENV['APP_STORE_CONNECT_TEAM_ID']}",
      export_options: {
        provisioningProfiles: {
          "za.co.bitlogiq.bittracker" => "match AppStore za.co.bitlogiq.bittracker"   # 👈 force profile match
        }
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
