name: iOS Pods (Flutter)

on:
  push:
  pull_request:

jobs:
  pods:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'

      - name: Flutter doctor
        run: flutter --version

      - name: Restore Flutter pub cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
            ${{ github.workspace }}/.packages
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Flutter pub get
        run: flutter pub get

      - name: Ensure Cocoapods up to date
        working-directory: ios
        run: |
          pod repo update

      - name: Pod install
        working-directory: ios
        run: pod install

      # Optional: try building to verify everything compiles
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign
