name: iOS TestFlight Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_URL: https://github.com/bitlogiq/ios-cert-store.git
      MATCH_GIT_BRANCH: main
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install fastlane
          brew install cocoapods
          pod install --project-directory=ios

      - name: Sync certs and profiles
        run: |
          fastlane match appstore \
            --readonly true \
            --git_url "$MATCH_GIT_URL" \
            --git_branch "$MATCH_GIT_BRANCH" \
            --git_basic_authorization "${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" \
            --app_identifier "$APP_IDENTIFIER" \
            --team_id "$TEAM_ID" \
            --username "$APPLE_ID"

      - name: Build and upload to TestFlight
        run: |
          cd ios
          bundle exec fastlane ios beta
