name: Seed iOS Certs (one-off)

on:
  workflow_dispatch: # manual trigger only

jobs:
  seed:
    runs-on: macos-14
    env:
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_URL: https://github.com/bitlogiq/ios-cert-store.git
      MATCH_GIT_BRANCH: main

    steps:
      - name: Checkout cert repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install fastlane
        run: gem install fastlane

      - name: Guard: ensure auth secret is present
        run: |
          if [ -z "${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" ]; then
            echo "❌ Missing secret MATCH_GIT_BASIC_AUTHORIZATION in ios-cert-store repo"; exit 1
          fi
          echo "✅ MATCH_GIT_BASIC_AUTHORIZATION detected"

      - name: Run fastlane match to generate and store certs (read-write)
        run: |
          fastlane match appstore \
            --readonly false \
            --git_url "$MATCH_GIT_URL" \
            --git_branch "$MATCH_GIT_BRANCH" \
            --git_basic_authorization "${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" \
            --app_identifier "$APP_IDENTIFIER" \
            --team_id "$TEAM_ID" \
            --username "$APPLE_ID"
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
